// Watch Face Builder Express server
// HTTP routing layer for the watch face builder backend.
// Complex business logic extracted to lib/build.js, lib/preview.js, and lib/design-store.js

// Load environment variables from .env file (if present)
require('dotenv').config();

const express = require('express');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const rateLimit = require('express-rate-limit');

const { getConfig } = require('./lib/config');
const { createLogger, logInfo, logError, logWarn } = require('./lib/logger');
const { buildProject, sweepExportDir } = require('./lib/build');

// Module-level pino logger — shared across all requests for this process lifetime.
const log = createLogger('server');
const { previewInSimulator } = require('./lib/preview');
const { saveDesign, listDesigns, loadDesign } = require('./lib/design-store');
const { buildQueue, designSaveQueue } = require('./lib/queue');
const { generateKey, getDefaultKeyPath } = require('./lib/keygen');
const { safePrgName } = require('./lib/naming');

// ─── Server factory ────────────────────────────────────────────────────────────
// Creates and returns an Express app with all routes configured.
// config: user config object with overrides (from electron-store or params)
// detectors: optional detector functions { detectSdkPath, getDefaultKeyPath } for auto-detection

function createServer(config = {}, detectors = {}) {
  const cfg = getConfig(config, detectors);
  const app = express();

  // Resolve designs directory once — cfg.designsDir is safe in both dev and packaged builds
  // because electron/main.js supplies app.getPath('userData'), never an ASAR path.
  const designsDir = cfg.designsDir;

  // Read once at startup — content is static; only the CSP nonce changes per request.
  const indexTemplate = fs.readFileSync(
    path.join(__dirname, 'builder', 'index.html'),
    'utf8'
  );

  // Startup sweep: delete export subdirectories older than 7 days.
  // Fire-and-forget — never blocks startup, never throws to caller.
  // Runs in both Electron and web-server modes since createServer() is the shared entry point.
  (async () => { await sweepExportDir(cfg.exportDir); })();

  // Enable proxy trust if running behind a reverse proxy
  app.set('trust proxy', 1);

  app.use(express.json({ limit: '10mb' }));

  // ── Request ID — attach before all routes so every log line is correlatable ──
  app.use((req, res, next) => {
    req.requestId = crypto.randomUUID();
    res.setHeader('x-request-id', req.requestId);
    next();
  });

  // ── Request lifecycle logging — start event + finish event with duration ──────
  app.use((req, res, next) => {
    const startMs = Date.now();
    const reqLog  = log.child({ requestId: req.requestId });

    reqLog.info({ event: 'request.start', method: req.method, path: req.path });

    res.on('finish', () => {
      const level = res.statusCode >= 500 ? 'error'
                  : res.statusCode >= 400 ? 'warn'
                  : 'info';
      reqLog[level]({
        event:      'request.end',
        method:     req.method,
        path:       req.path,
        status:     res.statusCode,
        durationMs: Date.now() - startMs,
      });
    });

    next();
  });

  // ── GET /health – Liveness probe for the Electron startup health gate ──────────
  // Registered before all other routes and before CSP middleware so it is always
  // fast and reachable even when other middleware is misconfigured.
  // No rate limiter: server binds to 127.0.0.1 only; this endpoint is not exposed
  // to external networks.
  app.get('/health', (req, res) => {
    res.json({ status: 'ok', pid: process.pid, ts: Date.now() });
  });

  // ─── Session token authentication ────────────────────────────────────────────
  // TOKEN is generated by electron/main.js at startup (crypto.randomBytes(32)) and
  // injected via WFB_SESSION_TOKEN env var. In standalone mode the caller must set
  // it manually. If not set, the middleware passes through (dev/test compatibility).
  // NEVER log the token value. Compare with timingSafeEqual to prevent timing attacks.
  const SESSION_TOKEN = process.env.WFB_SESSION_TOKEN || null;
  const expectedTokenBuf = SESSION_TOKEN ? Buffer.from(SESSION_TOKEN, 'hex') : null;

  if (!SESSION_TOKEN) {
    log.warn({
      event: 'auth.token_missing',
      message: 'WFB_SESSION_TOKEN is not set — API routes are UNPROTECTED. ' +
        'In Electron mode this is injected automatically. ' +
        'For standalone mode, set WFB_SESSION_TOKEN manually before starting.',
    });
  }

  function requireSessionToken(req, res, next) {
    // WFB_SESSION_TOKEN must be set. It is generated by electron/main.js and
    // injected into this process's environment before the server starts. If the
    // token is absent, the server started without Electron — a misconfiguration.
    if (!expectedTokenBuf) {
      log.error(
        { path: req.path, method: req.method },
        'Request rejected: WFB_SESSION_TOKEN not set. ' +
        'Server must be started via Electron, not directly via "npm run server".'
      );
      return res.status(401).json({
        error: 'Server misconfigured: session token not set.',
        hint: 'Start the application via "npm start" (Electron), not "npm run server".'
      });
    }

    const provided = req.headers['x-wfb-token'];

    if (!provided) {
      log.warn({ event: 'auth.rejected', reason: 'missing_token', route: req.path });
      return res.status(401).json({ error: 'Unauthorized', reason: 'Missing x-wfb-token header' });
    }

    let providedBuf;
    try {
      providedBuf = Buffer.from(provided, 'hex');
    } catch {
      return res.status(401).json({ error: 'Unauthorized', reason: 'Malformed token' });
    }

    if (
      providedBuf.length !== expectedTokenBuf.length ||
      !crypto.timingSafeEqual(providedBuf, expectedTokenBuf)
    ) {
      log.warn({ event: 'auth.rejected', reason: 'invalid_token', route: req.path });
      return res.status(401).json({ error: 'Unauthorized', reason: 'Invalid token' });
    }

    next();
  }

  // ─── Rate limiters ────────────────────────────────────────────────────────────
  const loadDesignLimiter = rateLimit({
    windowMs: 60000, // 60 seconds
    max: 30, // 30 requests max per IP
    standardHeaders: true, // Return rate limit info in `RateLimit-*` headers
    legacyHeaders: false, // Disable `X-RateLimit-*` headers
    handler: (req, res) => {
      res.status(429).json({ success: false, error: 'Too many design load requests' });
    }
  });

  const healthLimiter = rateLimit({
    windowMs: 60000, // 60 seconds
    max: 30, // 30 requests per IP — 12 polls/min + headroom for browser refreshes
    standardHeaders: true,
    legacyHeaders: false,
    handler: (req, res) => {
      res.status(429).json({ success: false, error: 'Too many health checks' });
    }
  });

  // Rate limiter for CPU/disk-intensive build endpoints.
  // 10 requests per 60 s is generous for interactive use but stops a CSRF flood
  // or a runaway renderer from queueing unbounded monkeyc/monkeydo child processes.
  const buildLimiter = rateLimit({
    windowMs: 60000, // 60 seconds
    max: 10,
    standardHeaders: true,
    legacyHeaders: false,
    handler: (req, res) => {
      res.setHeader('Retry-After', '60');
      res.status(429).json({ success: false, error: 'Too many build requests, please try again in a minute.' });
    }
  });

  // ─── Content Security Policy: nonce-based for stronger XSS protection ─────────
  app.use((req, res, next) => {
    // Generate a random nonce for this request
    const nonce = crypto.randomBytes(16).toString('base64');
    res.locals.nonce = nonce;

    // Content-Security-Policy header — authoritative CSP enforcement.
    // SYNC CONTRACT: builder/index.html contains a meta tag fallback (lines 4-32) that
    // must mirror this header on every update. The meta tag intentionally omits
    // 'strict-dynamic' and nonce because static HTML cannot embed a per-request nonce.
    // See CLAUDE.md §Content Security Policy for the CSP design rationale.
    res.setHeader(
      'Content-Security-Policy',
      `default-src 'self'; script-src 'self' 'strict-dynamic' 'nonce-${nonce}'; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'self'; worker-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none';`
    );
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('X-Frame-Options', 'DENY');
    res.setHeader('Referrer-Policy', 'no-referrer');
    res.setHeader('Permissions-Policy', 'geolocation=(), microphone=(), camera=()');
    next();
  });

  // ─── Serve index.html with nonce-injected script tags ─────────────────────────
  app.get('/', loadDesignLimiter, (req, res) => {
    // Inject per-request nonce into the cached template — do not cache the result
    const html = indexTemplate.replace(
      /<script type="module" src="app\.js"><\/script>/g,
      `<script type="module" src="app.js" nonce="${res.locals.nonce}"></script>`
    );
    res.set('Content-Type', 'text/html').send(html);
  });

  // ─── Serve static files (but not index.html, which is handled above) ──────────
  app.use(express.static(path.join(__dirname, 'builder'), {
    index: false // Disable default index.html serving
  }));

  // ── Route inventory ──────────────────────────────────────────────────────────
  // ROUTES (token required): GET /api/export/check/:name, POST /api/export,
  //   POST /api/save-design, GET /api/designs, GET /api/designs/check/:name,
  //   GET /api/designs/:filename, POST /api/preview, POST /api/generate-key
  // ROUTES (no token — called by Electron main process or health gate):
  //   GET /health (liveness probe), GET /api/health (SDK/key status for checkHealth())
  // PAGE ROUTES (no token — serve static HTML/CSS/JS, not sensitive API endpoints):
  //   GET /, static files middleware

  // ── GET /api/export/check/:projectName – Check if project exists ──
  // Updated for async traversal: readdirSync/lstatSync replaced with
  // fs.promises to prevent event loop blocking on large export trees.
  app.get('/api/export/check/:projectName', requireSessionToken, buildLimiter, async (req, res) => {
    try {
      const projectName = req.params.projectName;
      // Sanitize the incoming name with the same function used during export.
      // This ensures the collision check matches what the user will actually create.
      const prgName = safePrgName(projectName);
      const expectedFileName = `${prgName}.prg`;

      // Search for the .prg file in the export directory (recursively with depth limit).
      // Async version prevents event loop blocking during I/O waits.
      // Returns the directory containing the matching .prg file, or null if not found.
      // This allows post-retrieval cleanup to know exactly which requestId dir to delete.
      let foundInDir = null;
      try {
        const MAX_DEPTH = 10;
        const MAX_FILES_CHECKED = 10000;
        let filesChecked = 0;

        const findFileAsync = async (dir, currentDepth = 0) => {
          if (currentDepth > MAX_DEPTH) {
            throw new Error(`Export directory too deeply nested (max depth: ${MAX_DEPTH})`);
          }
          if (filesChecked++ > MAX_FILES_CHECKED) {
            throw new Error(`Too many files in export directory (searched ${MAX_FILES_CHECKED}+ files)`);
          }

          try {
            const files = await fs.promises.readdir(dir);
            for (const file of files) {
              const filePath = path.join(dir, file);
              let stat;
              try {
                stat = await fs.promises.lstat(filePath);
              } catch (err) {
                // Entry disappeared between readdir and lstat — skip it
                if (err.code === 'ENOENT') continue;
                throw err;
              }
              if (stat.isSymbolicLink()) {
                continue;
              } else if (stat.isDirectory()) {
                const found = await findFileAsync(filePath, currentDepth + 1);
                if (found) return found; // propagate the containing dir back up
              } else if (file === expectedFileName) {
                return dir; // return the directory that directly contains the .prg
              }
            }
          } catch (readErr) {
            logWarn('export-check:read-failed', { dir, reason: readErr.message });
          }
          return null;
        };

        if (fs.existsSync(cfg.exportDir)) {
          foundInDir = await findFileAsync(cfg.exportDir, 0);
        }
      } catch (searchErr) {
        res.status(400).json({ success: false, error: searchErr.message });
        return;
      }

      const exists = foundInDir !== null;
      res.json({ success: true, exists, projectName });

      // Strategy A — post-retrieval cleanup:
      // Defer deletion until after res.json() has queued the response body.
      // setImmediate fires after the current event loop tick, guaranteeing the
      // response is committed before any filesystem operation begins.
      // Deletion failure is logged but never surfaces to the client.
      if (exists) {
        // Derive the requestId-level directory: the immediate child of exportDir
        // that contains (or is) the directory where the .prg was found.
        const rel = path.relative(cfg.exportDir, foundInDir);
        const requestDir = path.join(cfg.exportDir, rel.split(path.sep)[0]);

        setImmediate(async () => {
          try {
            await fs.promises.rm(requestDir, { recursive: true, force: true });
            logInfo('export-check:cleanup', { requestDir: path.basename(requestDir) });
          } catch (err) {
            logWarn('export-check:cleanup-failed', { requestDir: path.basename(requestDir), reason: err.message });
          }
        });
      }
    } catch (err) {
      res.json({ success: false, error: err.message });
    }
  });

  // ── POST /api/export – Export and build .prg file ──
  app.post('/api/export', requireSessionToken, buildLimiter, async (req, res) => {
    const { elements = [], projectName = 'MyWatchFace' } = req.body;
    try {
      // Serialize builds: only one at a time (prevents file contention)
      const result = await buildQueue.add(
        () => buildProject(cfg, projectName, elements),
        `export:${projectName}`
      );
      // Strip server-side paths before sending to the client — prgPath, designPath,
      // and projectPath are internal and must not be disclosed over the wire.
      const { success, error, log, requestId } = result;
      res.json({ success, error, log, requestId });
    } catch (err) {
      if (err.message === 'Queue full — try again later') {
        res.set('Retry-After', '60');
        return res.status(503).json({ success: false, error: err.message, log: '', requestId: 'unknown' });
      }
      logError('export:queue-error', { reason: err.message });
      res.json({ success: false, error: err.message, log: '', requestId: 'unknown' });
    }
  });

  // ── POST /api/save-design – Save design to disk ──
  app.post('/api/save-design', requireSessionToken, buildLimiter, async (req, res) => {
    const { projectName = 'MyWatchFace', elements = [] } = req.body;
    try {
      // Serialize design saves: only one at a time (prevents overwrite loss)
      const result = await designSaveQueue.add(
        () => saveDesign(designsDir, projectName, elements),
        `save-design:${projectName}`
      );
      // Explicit allowlist — filePath excluded even as a basename; client needs only
      // success, projectName, and elementCount to confirm the save succeeded.
      const { success, projectName: savedName, elementCount, error } = result;
      res.json({ success, projectName: savedName, elementCount, error });
    } catch (err) {
      if (err.message === 'Queue full — try again later') {
        res.set('Retry-After', '60');
        return res.status(503).json({ success: false, error: err.message, log: '' });
      }
      logError('save-design:queue-error', { reason: err.message });
      res.json({ success: false, error: err.message, log: '' });
    }
  });

  // ── GET /api/designs – List all saved designs ──
  app.get('/api/designs', requireSessionToken, loadDesignLimiter, async (req, res) => {
    try {
      const designs = await listDesigns(designsDir);
      res.json({ success: true, designs });
    } catch (err) {
      logError('designs:list-error', { reason: err.message });
      res.json({ success: false, error: err.message });
    }
  });

  // ── GET /api/designs/check/:projectName – Check if design exists ──
  app.get('/api/designs/check/:projectName', requireSessionToken, loadDesignLimiter, (req, res) => {
    try {
      const projectName = req.params.projectName;
      const fileName = `${safePrgName(projectName)}.json`;
      const exists = fs.existsSync(path.join(designsDir, fileName));

      res.json({ success: true, exists, projectName });
    } catch (err) {
      res.json({ success: false, error: err.message });
    }
  });

  // ── GET /api/designs/:filename – Load a specific design ──
  app.get('/api/designs/:filename', requireSessionToken, loadDesignLimiter, (req, res) => {
    try {
      const design = loadDesign(designsDir, req.params.filename);
      res.json({
        success: true,
        design,
        validationWarning: design.validationWarning || null,
        requiresConfirmation: design.requiresConfirmation || false,
      });
    } catch (err) {
      logError('designs:load-error', { reason: err.message });
      res.json({ success: false, error: err.message });
    }
  });

  // ── POST /api/preview – Build and launch in simulator ──
  app.post('/api/preview', requireSessionToken, buildLimiter, async (req, res) => {
    const { elements = [], projectName = 'WatchFacePreview' } = req.body;
    try {
      // Serialize builds: only one at a time (prevents file contention)
      const buildResult = await buildQueue.add(
        () => buildProject(cfg, projectName, elements),
        `preview:${projectName}`
      );
      if (!buildResult.success) {
        return res.json(buildResult);
      }
      // Fire off preview work asynchronously (simulator launch, .prg loading)
      // Pass requestId to ensure temp files don't collide if multiple previews run
      previewInSimulator(cfg, buildResult.prgPath, buildResult.requestId);
      res.json({ success: true, message: 'Starting simulator…', log: buildResult.log, requestId: buildResult.requestId });
    } catch (err) {
      if (err.message === 'Queue full — try again later') {
        res.set('Retry-After', '60');
        return res.status(503).json({ success: false, error: err.message, log: '', requestId: 'unknown' });
      }
      logError('preview:queue-error', { reason: err.message });
      res.json({ success: false, error: err.message, log: '', requestId: 'unknown' });
    }
  });

  // ── POST /api/generate-key – Generate a developer key (web mode; Electron uses IPC) ──
  app.post('/api/generate-key', requireSessionToken, buildLimiter, async (req, res) => {
    const outputPath = cfg.devKey || getDefaultKeyPath();
    const force = req.body?.force === true;

    if (!force && fs.existsSync(outputPath)) {
      return res.json({ success: false, exists: true, path: outputPath });
    }

    try {
      const result = await generateKey(outputPath);
      logInfo('Developer key generated', { path: result.path });
      res.json({ success: true, path: result.path });
    } catch (err) {
      logError('Key generation failed', { error: err.message });
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // ── GET /api/health – Health check for Electron startup validation ──
  app.get('/api/health', healthLimiter, (req, res) => {
    const health = {
      ok: fs.existsSync(cfg.monkeyc) && fs.existsSync(cfg.devKey),
      sdkFound: fs.existsSync(cfg.monkeyc),
      keyFound: fs.existsSync(cfg.devKey),
      timestamp: new Date().toISOString(),
    };
    res.status(health.ok ? 200 : 503).json({ ...health, buildQueue: buildQueue.stats() });
  });

  return app;
}

// ─── Exports and direct invocation ────────────────────────────────────────────

module.exports = { createServer, getConfig };

// Allow direct execution: node server.js (standalone mode — npm run server)
if (require.main === module) {
  // Standalone execution guard.
  // The production path is: Electron main process generates WFB_SESSION_TOKEN,
  // injects it into this process's env, then spawns this file. Running
  // "npm run server" directly is only valid for CI/integration testing where
  // the token is explicitly set in the environment before startup.
  //
  // Per CLAUDE.md §Server security contract: "The server exits with code 1
  // if started standalone without the token."
  if (!process.env.WFB_SESSION_TOKEN) {
    process.stderr.write(
      '\n' +
      '[server] FATAL: WFB_SESSION_TOKEN is not set.\n' +
      '[server] The server requires a session token to prevent unauthenticated\n' +
      '[server] access to the Monkey C build pipeline.\n' +
      '[server]\n' +
      '[server] NORMAL PATH: Start the application via "npm start" (Electron mode).\n' +
      '[server] Electron generates the token and injects it automatically.\n' +
      '[server]\n' +
      '[server] CI/TESTING PATH: Set WFB_SESSION_TOKEN before "npm run server".\n' +
      '[server] Example:\n' +
      '[server]   PowerShell:\n' +
      '[server]     $env:WFB_SESSION_TOKEN = ' +
      'node -e "process.stdout.write(require(\'crypto\').randomBytes(32).toString(\'hex\'))"\n' +
      '[server]     npm run server\n' +
      '[server]   bash:\n' +
      '[server]     export WFB_SESSION_TOKEN=$(node -e ' +
      '"process.stdout.write(require(\'crypto\').randomBytes(32).toString(\'hex\'))")\n' +
      '[server]     npm run server\n' +
      '\n'
    );
    process.exit(1);
  }

  // WFB_SERVER_PORT is set by the Electron main process when spawning this script.
  // In standalone mode it falls back to 3000. See docs/architecture.md §Port Configuration.
  const PORT = parseInt(process.env.WFB_SERVER_PORT, 10) || 3000;
  const expressApp = createServer();
  const server = expressApp.listen(PORT, '127.0.0.1', () => {
    // Emit the structured startup log. The Electron health gate polls GET /health via HTTP —
    // it does NOT parse this log line, so format changes here are safe.
    const cfg = getConfig();
    log.info({
      event:   'server.ready',
      host:    '127.0.0.1',
      port:    PORT,
      sdkBin:  path.basename(path.dirname(cfg.sdkBin)),
      devKey:  path.basename(cfg.devKey),
      exports: path.basename(cfg.exportDir),
    });
  });

  // Clean shutdown on SIGTERM (sent by Electron main process via before-quit handler).
  // TODO(win32): serverProcess.kill() sends SIGKILL on Windows, not SIGTERM — this
  // handler will not fire on Windows. Graceful Win32 shutdown via named pipe or IPC
  // message is tracked in docs/architecture.md §Known Limitations.
  process.on('SIGTERM', () => {
    log.info({ event: 'server.sigterm', message: 'received SIGTERM — closing' });
    server.close(() => {
      process.exit(0);
    });
  });
}
