// Security middleware: request ID, logging, token validation, trust proxy

const crypto = require('crypto');
const express = require('express');

function createSecurityMiddleware(log) {
  // ── Trust proxy – required when running behind reverse proxy ────
  function trustProxy(req, res, next) {
    req.app.set('trust proxy', 1);
    next();
  }

  // ── Request ID – attach before all routes ────
  function requestId(req, res, next) {
    req.requestId = crypto.randomUUID();
    res.setHeader('x-request-id', req.requestId);
    next();
  }

  // ── Request lifecycle logging ────
  function requestLogging(req, res, next) {
    const startMs = Date.now();
    const reqLog = log.child({ requestId: req.requestId });

    reqLog.info({ event: 'request.start', method: req.method, path: req.path });

    res.on('finish', () => {
      const level = res.statusCode >= 500 ? 'error'
                  : res.statusCode >= 400 ? 'warn'
                  : 'info';
      reqLog[level]({
        event: 'request.end',
        method: req.method,
        path: req.path,
        status: res.statusCode,
        durationMs: Date.now() - startMs,
      });
    });

    next();
  }

  // ── Session token authentication ────
  // TOKEN is generated by electron/main.js (crypto.randomBytes(32)) and injected via WFB_SESSION_TOKEN env var.
  // In standalone mode, the caller must set it manually.
  // If not set, this middleware returns 401 — it never passes through.
  // NEVER log the token value. Compare with timingSafeEqual to prevent timing attacks.
  function createRequireSessionToken(sessionToken) {
    const expectedTokenBuf = sessionToken ? Buffer.from(sessionToken, 'hex') : null;

    return (req, res, next) => {
      // If no token is configured, reject all requests (misconfiguration error).
      if (!expectedTokenBuf) {
        return res.status(401).json({
          error: 'Unauthorized',
          reason: 'Server not configured with session token',
        });
      }

      const tokenHeader = req.headers['x-wfb-token'];
      if (!tokenHeader) {
        return res.status(401).json({
          error: 'Unauthorized',
          reason: 'Missing x-wfb-token header',
        });
      }

      let tokenBuf;
      try {
        tokenBuf = Buffer.from(tokenHeader, 'hex');
      } catch {
        return res.status(401).json({
          error: 'Unauthorized',
          reason: 'Invalid token encoding',
        });
      }

      // Use timingSafeEqual to prevent timing attacks
      if (tokenBuf.length !== expectedTokenBuf.length || !crypto.timingSafeEqual(tokenBuf, expectedTokenBuf)) {
        return res.status(401).json({
          error: 'Unauthorized',
          reason: 'Invalid token',
        });
      }

      next();
    };
  }

  return {
    trustProxy,
    jsonParser: express.json({ limit: '10mb' }),
    requestId,
    requestLogging,
    createRequireSessionToken,
  };
}

module.exports = { createSecurityMiddleware };
